### ISSUE TITLE
Deluge version 2 might have broken deluge-siphon

### ISSUE THREAD

**Issue by scatat** [sbussetti/deluge-siphon#80]
Hi - thanks for this great tool. I recently updated my deluge server to version 2. I think that this has broken deluge-siphon. It's affected things like radarr as well so I supposed I should not be surprised!

**Comment by kolinger** [comment]
Some torrents work for me and others don't. If I try to add not working torrent directly to deluge-web ui it doesn't work either and deluge is failing (with extension and directly) with error "'utf-8' codec can't decode byte 0x9d in position 336: invalid start byte". Seems like deluge has issues with downloading some torrents by URL.

Try to "Add torrent" by URL directly with deluge-web. Maybe you have same issues as I have. In that case this is problem with deluge itself and not with this extension.

**Comment by scatat** [comment]
Thank you. Actually, I think it's alright for most magnet files. Odd. I'll feedback when I have more info

**Comment by netvyper** [comment]
I'm having similar issues with Deluge 2.0. All torrents seem to throw errors, but they do get added to Deluge. Happy to debug further if you tell me what you need.

**Comment by cjlee89** [comment]
I have this issue as well since Deluge 2.0. Using 2.0.3 to be exact.

**Comment by cjlee89** [comment]
@sbussetti Have you reproduced this since Deluge version 2.0?

**Comment by sbussetti** [comment]
working on getting deluge 2 in a test setup so I can verify and work on compat

**Comment by cjlee89** [comment]
Let me know if you need any testing done.

**Comment by ksa-real** [comment]
I've installed deluge on Arch linux (v 2.0.4.dev38). For some reason deluged-siphon doesn't work anymore.
I've checked the service logs:
```
Aug 02 15:30:56 site deluged[3145]: /usr/lib/python3.8/site-packages/twisted/web/_newclient.py:1673:_disconnectParser
Aug 02 15:30:56 site deluged[3145]: --- <exception caught here> ---
Aug 02 15:30:56 site deluged[3145]: /usr/lib/python3.8/site-packages/twisted/web/_newclient.py:567:connectionLost
Aug 02 15:30:56 site deluged[3145]: /usr/lib/python3.8/site-packages/twisted/web/_newclient.py:1050:dispatcher
Aug 02 15:30:56 site deluged[3145]: /usr/lib/python3.8/site-packages/twisted/web/_newclient.py:1306:_bodyDataFinished_CONNECTED
Aug 02 15:30:56 site deluged[3145]: /usr/lib/python3.8/site-packages/twisted/web/client.py:2025:connectionLost
Aug 02 15:30:56 site deluged[3145]: /usr/lib/python3.8/site-packages/deluge/httpdownloader.py:75:connectionLost
Aug 02 15:30:56 site deluged[3145]: /usr/lib/python3.8/encodings/cp1251.py:15:decode
Aug 02 15:30:56 site deluged[3145]: ]
Aug 02 15:32:33 site deluged[3145]: Traceback (most recent call last):
Aug 02 15:32:33 site deluged[3145]:   File "/usr/lib/python3.8/site-packages/twisted/web/_newclient.py", line 1050, in dispatcher
Aug 02 15:32:33 site deluged[3145]:     return func(*args, **kwargs)
Aug 02 15:32:33 site deluged[3145]:   File "/usr/lib/python3.8/site-packages/twisted/web/_newclient.py", line 1632, in _finishResponse_WAITING
Aug 02 15:32:33 site deluged[3145]:     self._giveUp(Failure(reason))
Aug 02 15:32:33 site deluged[3145]:   File "/usr/lib/python3.8/site-packages/twisted/web/_newclient.py", line 1685, in _giveUp
Aug 02 15:32:33 site deluged[3145]:     self._disconnectParser(reason)
Aug 02 15:32:33 site deluged[3145]:   File "/usr/lib/python3.8/site-packages/twisted/web/_newclient.py", line 1673, in _disconnectParser
Aug 02 15:32:33 site deluged[3145]:     parser.connectionLost(reason)
Aug 02 15:32:33 site deluged[3145]: --- <exception caught here> ---
Aug 02 15:32:33 site deluged[3145]:   File "/usr/lib/python3.8/site-packages/twisted/web/_newclient.py", line 567, in connectionLost
Aug 02 15:32:33 site deluged[3145]:     self.response._bodyDataFinished()
Aug 02 15:32:33 site deluged[3145]:   File "/usr/lib/python3.8/site-packages/twisted/web/_newclient.py", line 1050, in dispatcher
Aug 02 15:32:33 site deluged[3145]:     return func(*args, **kwargs)
Aug 02 15:32:33 site deluged[3145]:   File "/usr/lib/python3.8/site-packages/twisted/web/_newclient.py", line 1306, in _bodyDataFinished_CONNECTED
Aug 02 15:32:33 site deluged[3145]:     self._bodyProtocol.connectionLost(reason)
Aug 02 15:32:33 site deluged[3145]:   File "/usr/lib/python3.8/site-packages/twisted/web/client.py", line 2025, in connectionLost
Aug 02 15:32:33 site deluged[3145]:     self.original.connectionLost(reason)
Aug 02 15:32:33 site deluged[3145]:   File "/usr/lib/python3.8/site-packages/deluge/httpdownloader.py", line 75, in connectionLost
Aug 02 15:32:33 site deluged[3145]:     self.data = self.data.decode(self.encoding).encode('utf8')
Aug 02 15:32:33 site deluged[3145]:   File "/usr/lib/python3.8/encodings/cp1251.py", line 15, in decode
Aug 02 15:32:33 site deluged[3145]:     return codecs.charmap_decode(input,errors,decoding_table)
Aug 02 15:32:33 site deluged[3145]: builtins.UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 872: character maps to <undefined>
Aug 02 15:32:33 site deluged[3145]: 15:32:33.177 [CRITICAL][deluge.log                    :93  ] twisted.web._newclient.HTTPClientParser
Aug 02 15:32:33 site deluged[3145]: [Failure instance: Traceback: <class 'UnicodeDecodeError'>: 'charmap' codec can't decode byte 0x98 in position 872: character maps to <>
Aug 02 15:32:33 site deluged[3145]: /usr/lib/python3.8/site-packages/twisted/web/_newclient.py:1050:dispatcher
Aug 02 15:32:33 site deluged[3145]: /usr/lib/python3.8/site-packages/twisted/web/_newclient.py:1632:_finishResponse_WAITING
Aug 02 15:32:33 site deluged[3145]: /usr/lib/python3.8/site-packages/twisted/web/_newclient.py:1685:_giveUp
Aug 02 15:32:33 site deluged[3145]: /usr/lib/python3.8/site-packages/twisted/web/_newclient.py:1673:_disconnectParser
Aug 02 15:32:33 site deluged[3145]: --- <exception caught here> ---
Aug 02 15:32:33 site deluged[3145]: /usr/lib/python3.8/site-packages/twisted/web/_newclient.py:567:connectionLost
Aug 02 15:32:33 site deluged[3145]: /usr/lib/python3.8/site-packages/twisted/web/_newclient.py:1050:dispatcher
Aug 02 15:32:33 site deluged[3145]: /usr/lib/python3.8/site-packages/twisted/web/_newclient.py:1306:_bodyDataFinished_CONNECTED
Aug 02 15:32:33 site deluged[3145]: /usr/lib/python3.8/site-packages/twisted/web/client.py:2025:connectionLost
Aug 02 15:32:33 site deluged[3145]: /usr/lib/python3.8/site-packages/deluge/httpdownloader.py:75:connectionLost
Aug 02 15:32:33 site deluged[3145]: /usr/lib/python3.8/encodings/cp1251.py:15:decode
```
It looks like deluged fails to download torrent file given the data from deluge-siphon.

**Comment by sbussetti** [comment]
it's not compatible with deluge 2 yet, I need to release an update.  Thanks for the stack trace.

**Comment by ksa-real** [comment]
@sbussetti Any chances you'll take a look at this?

**Comment by ksa-real** [comment]
I went ahead and debugged the issue. It appeared to be a problem with the deluge itself. Filed the ticket and the patch here: https://dev.deluge-torrent.org/ticket/3440
It's ok to close the ticket.

**Comment by madmattco** [comment]
> it's not compatible with deluge 2 yet, I need to release an update. Thanks for the stack trace.

I know its been a while. Any sort of update?
